# Default initial positions for humanoid's ros2_control fake system

initial_positions:
  elbow_l_joint: 0
  elbow_r_joint: 0
  left_joint1: 0
  left_joint3: 0
  left_joint5: 0
  left_joint6: 0
  left_joint7: 0
  right_joint1: 0
  right_joint3: 0
  right_joint5: 0
  right_joint6: 0
  right_joint7: 0
  shoulder_roll_l_joint: 0
  shoulder_roll_r_joint: 0