# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    leftArm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rightArm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

leftArm_controller:
  ros__parameters:
    joints:
      - left_joint1
      - shoulder_roll_l_joint
      - left_joint3
      - elbow_l_joint
      - left_joint5
      - left_joint6
      - left_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
rightArm_controller:
  ros__parameters:
    joints:
      - right_joint1
      - shoulder_roll_r_joint
      - right_joint3
      - elbow_r_joint
      - right_joint5
      - right_joint6
      - right_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity